// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: src/prover-input/proto/extra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Extra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessList    []*AccessTuple         `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	StateDiffs    []*StateDiff           `protobuf:"bytes,2,rep,name=state_diffs,json=stateDiffs,proto3" json:"state_diffs,omitempty"`
	Committed     [][]byte               `protobuf:"bytes,3,rep,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extra) Reset() {
	*x = Extra{}
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extra) ProtoMessage() {}

func (x *Extra) ProtoReflect() protoreflect.Message {
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extra.ProtoReflect.Descriptor instead.
func (*Extra) Descriptor() ([]byte, []int) {
	return file_src_prover_input_proto_extra_proto_rawDescGZIP(), []int{0}
}

func (x *Extra) GetAccessList() []*AccessTuple {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *Extra) GetStateDiffs() []*StateDiff {
	if x != nil {
		return x.StateDiffs
	}
	return nil
}

func (x *Extra) GetCommitted() [][]byte {
	if x != nil {
		return x.Committed
	}
	return nil
}

type StateDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PreAccount    *Account               `protobuf:"bytes,2,opt,name=pre_account,json=preAccount,proto3" json:"pre_account,omitempty"`
	PostAccount   *Account               `protobuf:"bytes,3,opt,name=post_account,json=postAccount,proto3" json:"post_account,omitempty"`
	Storage       []*StorageDiff         `protobuf:"bytes,4,rep,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateDiff) Reset() {
	*x = StateDiff{}
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateDiff) ProtoMessage() {}

func (x *StateDiff) ProtoReflect() protoreflect.Message {
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateDiff.ProtoReflect.Descriptor instead.
func (*StateDiff) Descriptor() ([]byte, []int) {
	return file_src_prover_input_proto_extra_proto_rawDescGZIP(), []int{1}
}

func (x *StateDiff) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *StateDiff) GetPreAccount() *Account {
	if x != nil {
		return x.PreAccount
	}
	return nil
}

func (x *StateDiff) GetPostAccount() *Account {
	if x != nil {
		return x.PostAccount
	}
	return nil
}

func (x *StateDiff) GetStorage() []*StorageDiff {
	if x != nil {
		return x.Storage
	}
	return nil
}

type StorageDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          []byte                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	PreValue      []byte                 `protobuf:"bytes,2,opt,name=pre_value,json=preValue,proto3" json:"pre_value,omitempty"`
	PostValue     []byte                 `protobuf:"bytes,3,opt,name=post_value,json=postValue,proto3" json:"post_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDiff) Reset() {
	*x = StorageDiff{}
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDiff) ProtoMessage() {}

func (x *StorageDiff) ProtoReflect() protoreflect.Message {
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDiff.ProtoReflect.Descriptor instead.
func (*StorageDiff) Descriptor() ([]byte, []int) {
	return file_src_prover_input_proto_extra_proto_rawDescGZIP(), []int{2}
}

func (x *StorageDiff) GetSlot() []byte {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *StorageDiff) GetPreValue() []byte {
	if x != nil {
		return x.PreValue
	}
	return nil
}

func (x *StorageDiff) GetPostValue() []byte {
	if x != nil {
		return x.PostValue
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       []byte                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	CodeHash      []byte                 `protobuf:"bytes,2,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	StorageHash   []byte                 `protobuf:"bytes,4,opt,name=storage_hash,json=storageHash,proto3" json:"storage_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_src_prover_input_proto_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_src_prover_input_proto_extra_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Account) GetCodeHash() []byte {
	if x != nil {
		return x.CodeHash
	}
	return nil
}

func (x *Account) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Account) GetStorageHash() []byte {
	if x != nil {
		return x.StorageHash
	}
	return nil
}

var File_src_prover_input_proto_extra_proto protoreflect.FileDescriptor

var file_src_prover_input_proto_extra_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2d, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x28, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x2d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12,
	0x33, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x69,
	0x66, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x66, 0x66, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x66, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a,
	0x0b, 0x70, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31,
	0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x44, 0x69, 0x66, 0x66, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22,
	0x5d, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x44, 0x69, 0x66, 0x66, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x79,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x48, 0x61, 0x73, 0x68, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6b, 0x72, 0x74, 0x2d, 0x6c, 0x61, 0x62,
	0x73, 0x2f, 0x7a, 0x6b, 0x2d, 0x70, 0x69, 0x67, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x72, 0x2d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_prover_input_proto_extra_proto_rawDescOnce sync.Once
	file_src_prover_input_proto_extra_proto_rawDescData = file_src_prover_input_proto_extra_proto_rawDesc
)

func file_src_prover_input_proto_extra_proto_rawDescGZIP() []byte {
	file_src_prover_input_proto_extra_proto_rawDescOnce.Do(func() {
		file_src_prover_input_proto_extra_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_prover_input_proto_extra_proto_rawDescData)
	})
	return file_src_prover_input_proto_extra_proto_rawDescData
}

var file_src_prover_input_proto_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_prover_input_proto_extra_proto_goTypes = []any{
	(*Extra)(nil),       // 0: input.Extra
	(*StateDiff)(nil),   // 1: input.StateDiff
	(*StorageDiff)(nil), // 2: input.StorageDiff
	(*Account)(nil),     // 3: input.Account
	(*AccessTuple)(nil), // 4: input.AccessTuple
}
var file_src_prover_input_proto_extra_proto_depIdxs = []int32{
	4, // 0: input.Extra.access_list:type_name -> input.AccessTuple
	1, // 1: input.Extra.state_diffs:type_name -> input.StateDiff
	3, // 2: input.StateDiff.pre_account:type_name -> input.Account
	3, // 3: input.StateDiff.post_account:type_name -> input.Account
	2, // 4: input.StateDiff.storage:type_name -> input.StorageDiff
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_src_prover_input_proto_extra_proto_init() }
func file_src_prover_input_proto_extra_proto_init() {
	if File_src_prover_input_proto_extra_proto != nil {
		return
	}
	file_src_prover_input_proto_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_prover_input_proto_extra_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_prover_input_proto_extra_proto_goTypes,
		DependencyIndexes: file_src_prover_input_proto_extra_proto_depIdxs,
		MessageInfos:      file_src_prover_input_proto_extra_proto_msgTypes,
	}.Build()
	File_src_prover_input_proto_extra_proto = out.File
	file_src_prover_input_proto_extra_proto_rawDesc = nil
	file_src_prover_input_proto_extra_proto_goTypes = nil
	file_src_prover_input_proto_extra_proto_depIdxs = nil
}
